name: IaC avec Bicep

on: workflow_dispatch

env:
  RG_NAME: RG-Test-WhatIf
  LOCATION: westeurope

jobs:
  Build-IaC:
    runs-on: ubuntu-20.04

    steps:
      - name: Check Bicep
        run: |
          az bicep install

      - name: Recuperation du repo
        uses: Actions/checkout@v2

      - name: Build en "json"
        run: |
          az bicep build --files ./Bicep/main.bicep

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Creation du RG pour test
        run: |
          az group create --name ${{ env.RG_NAME }} --location ${{ env.LOCATION }}

      - name: WhatIf Template ARM
        run: |
          az deployment group what-if --resource-group ${{ env.RG_NAME }} --template-file ./Bicep/main.json                  

      - name: Artifacts json
        uses: actions/upload-artifact@v1
        with:
          name: arm_template
          path: ./Bicep/main.json